#BNF+IAT 1.0 UTF-8;
!grammar voiceadjust;
!slot <callCmd>;
!slot <contact>;
!slot <callCmdmax>;
!slot <contactmin>;
!start <callStart>;
<callStart>:<callCmd>|<contact>|<callCmdmax>|<contactmin>;
<callCmd>:加大音量|增加音量|调大音量;
<contact>:减小音量|调小音量;
<callCmdmax>:音量加到最大|最大音量;
<contactmin>:音量减到最小|最小音量;